### ISSUE TITLE
[Feature request] CUB

### ISSUE THREAD

**Issue by prlz77** [tristandeleu/pytorch-meta#10]
Hi! do you plan to add CUB birds in the future? Feel free to delete this issue if it is not the proper place to ask.

Have a nice day,

Pau

**Comment by tristandeleu** [comment]
Hi Pau! I would love to add CUB, but I haven't been able to find a standard split for meta-train/meta-test classes. From what I have seen in papers using CUB, a random split is generally used for meta-train/meta-test, which might be an issue for reproducibility. The closest I can find from a fixed split is the way @wyharveychen created the split [here](https://github.com/wyharveychen/CloserLookFewShot/blob/master/filelists/CUB/write_CUB_filelist.py).

If we can all agree on this meta-train/meta-validation/meta-test split as being standard, then I'd be very happy to add CUB! I'm pinging @nhilliard & @wyharveychen for discussion.

**Comment by prlz77** [comment]
Thanks! I am currently using the split you are pointing to. But I agree it is a very recent dataset in the few-shot literature.

**Comment by vmichals** [comment]
Here's another publication using the split by @wyharveychen: [Shaping Visual Representations with Language for Few-shot Classification](https://arxiv.org/abs/1911.02683).

I think it can considered a reasonable choice for a standard split.

**Comment by tristandeleu** [comment]
I have added the CUB dataset in Torchmeta 1.2.0, with the split above.
