### ISSUE TITLE
PyTorch 1.7

### ISSUE THREAD

**Issue by fablos** [tristandeleu/pytorch-meta#101]
Hi, with PyTorch 1.7 released yesterday I was wondering whether there is any known issue that would prevent us to use pytorch-meta with this new version. 
Thanks

**Comment by tristandeleu** [comment]
I haven't tested it with PyTorch 1.7 yet, but going through the changelog it looks like Torchmeta should be compatible with 1.7. I'm going to properly run the tests and push a new version.

**Comment by tristandeleu** [comment]
I have pushed Torchmeta 1.6.0 which is compatible with PyTorch 1.7.
