### ISSUE TITLE
max examples per class omniglot?

### ISSUE THREAD

**Issue by bbc1183** [tristandeleu/pytorch-meta#106]
Am I right to assume that the maximum number of examples you can use for k-shot learning on omniglot is 5?  If I set (shots > 5) I get an error.

**Comment by tristandeleu** [comment]
From memory, the number of examples per class in Omniglot is 20, so you should not get any error when `shots > 5` (as long as `shots + test_shots <= 20`)

**Comment by bbc1183** [comment]
ahhh, i was missing (as long as shots + test_shots <= 20).  thanks so much.
