### ISSUE TITLE
How to download the dataset manually?

### ISSUE THREAD

**Issue by Dreamcreationman** [tristandeleu/pytorch-meta#119]
I have trouble downloading with the code provided and error msg shows as follows:

`requests.exceptions.ConnectionError: HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=16V_ZlkW4SsnNDtnGmaBRq2OoPmUOc5mY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb5c0741460>: Failed to establish a new connection: [Errno 110] Connection timed out'))
`

**Comment by tristandeleu** [comment]
Downloading the data manually is a bit difficult because it is specific to each dataset. However you can look at the `download()` method for the dataset you'd like to download in order to retrieve the download URL (e.g. a Google Drive ID).
