### ISSUE TITLE
MAML checkpoint for 5CNN on mini-imagenet

### ISSUE THREAD

**Issue by brando90** [tristandeleu/pytorch-meta#122]
hi Tristand, I remember you mentioned that you did reproduce the 63% acc that MAML got on mini-imagenet to test your torchmeta library. I was wondering if you had that checkpoint available?

Thanks for your time.

**Comment by tristandeleu** [comment]
I was able to reproduce the 63% meta-test accuracy on MiniImagenet using [https://github.com/tristandeleu/pytorch-maml](https://github.com/tristandeleu/pytorch-maml). I thought about sharing checkpoints at some point (this was asked before), but I prefer to not share a checkpoint to avoid having to maintain it sorry. That being said, you should be able to reproduce these results fairly easily using this other repo.

**Comment by brando90** [comment]
> I was able to reproduce the 63% meta-test accuracy on MiniImagenet using https://github.com/tristandeleu/pytorch-maml. I thought about sharing checkpoints at some point (this was asked before), but I prefer to not share a checkpoint to avoid having to maintain it sorry. That being said, you should be able to reproduce these results fairly easily using this other repo.

What does it mean you do not want to maintain the checkpoint?
