### ISSUE TITLE
Questions about downloading datasets

### ISSUE THREAD

**Issue by liguge** [tristandeleu/pytorch-meta#133]
I am a novice, and I have only been exposed to this subject not long . Your code is of great reference for my understanding of meta-learning. When I run the code, the following error is displayed. After searching for a long time, I haven't found how to solve it. I want to ask for advice. thanks

sage: Model-Agnostic Meta-Learning (MAML) [-h] [--num-shots NUM_SHOTS]
                                           [--num-ways NUM_WAYS]
                                           [--first-order]
                                           [--step-size STEP_SIZE]
                                           [--hidden-size HIDDEN_SIZE]
                                           [--output-folder OUTPUT_FOLDER]
                                           [--batch-size BATCH_SIZE]
                                           [--num-batches NUM_BATCHES]
                                           [--num-workers NUM_WORKERS]
                                           [--download] [--use-cuda]
                                           folder
Model-Agnostic Meta-Learning (MAML): error: the following arguments are required: folder

**Comment by tristandeleu** [comment]
I'm sorry for the late reply. The `folder` argument is the path to the folder where the dataset (Omniglot here) is. For example, you can run it as
```bash
python maml.py data --num-shots 5 --num-ways 5 --download
```
That will download the dataset into the `data/omniglot` folder.
