### ISSUE TITLE
pip install torchmeta

### ISSUE THREAD

**Issue by Ayiing** [tristandeleu/pytorch-meta#135]
after
'''
pip install torchmeta
'''
i run the code
'''
from torchmeta.modules.utils import get_subdict
'''
it ocurred
'''
ModuleNotFoundError: No module named 'torchmeta.modules.utils'
'''
thanks

**Comment by tristandeleu** [comment]
The `torchmeta.modules.utils` module does not exist anymore, it has been replaced by the method [`get_subdict` method in `MetaModule`](https://github.com/tristandeleu/pytorch-meta/blob/d487ad0a1268bd6e6a7290b8780c6b62c7bed688/torchmeta/modules/module.py#L36-L63).

**Comment by Ayiing** [comment]
thanks!!
