### ISSUE TITLE
request to be contributors

### ISSUE THREAD

**Issue by Franklin-Yao** [tristandeleu/pytorch-meta#16]
Hi,

I am a Phd student and working on few shot learning. This is an exciting project. Can i contribute for it? Although you have done a lot, there should be more we can do?

**Comment by xcmax** [comment]
I found lots of meta learning methods have backbone networks like Conv32, conv64, resnet12 and resnet18 but details are a little bit different. For example, some have more layers, more filters than others.Maybe we can standardize it and integrate this part to torchmeta for fair comparison

**Comment by tristandeleu** [comment]
Apologies for the very late reply. Any kind of help is very welcome, and thank you for volunteering!
I think having standard backbone networks here would be a great idea. If you add them, please include some previous papers that use them to keep track.

Another area that always requires more work is adding datasets. Some of which were suggested here #17.

I am closing this issue for now, but feel free to open other issues or PRs depending on what you want to add to Torchmeta.
