### ISSUE TITLE
Conv2d bias kwarg

### ISSUE THREAD

**Issue by deltaskelta** [tristandeleu/pytorch-meta#19]
I had some trouble replicating the results from the MAML paper when using torchmeta, and your example and your other MAML repo as references. I am searching for the problem and I found that the MetaConv2d deviates from the pytorch Conv2d layer because of this line. 

https://github.com/tristandeleu/pytorch-meta/blob/96ad5703414ef983b56d3c396a944829707ff076/torchmeta/modules/conv.py#L14

if I replicate that situation in a function it turns out like this which would mean that the default value for bias has been changed to a falsey value in this function

```
def foo(kwarg=True):
  print(kwarg)

foo(kwarg=None)
# output: None
foo()
# output: True
``` 

Should we change it to or does that change the function in some other way?

```
bias = params.get('bias', True)
```

**Comment by tristandeleu** [comment]
I don't think that would do the trick. Having `params.get('bias', None)` means that if you don't have any bias in your parameter dict (setting `bias=False` when creating you layer), then bias is set to `None`. This is similar to [the way `self.bias` is created when instantiating](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/conv.py#L48-L51).

**Comment by deltaskelta** [comment]
hmm yes you are right, I should have checked deeper. Sorry, my mistake
