### ISSUE TITLE
Reproducing results

### ISSUE THREAD

**Issue by eugenelet** [tristandeleu/pytorch-meta#26]
Hi there, I'd like to ask if it's possible to include tabulated data comparing different approaches using different datasets as found in [meta_dataset](https://github.com/google-research/meta-dataset#models-trained-on-ilsvrc-2012-only)? Since some papers doesn't use the same split between training, validation and testing, re-implementation is required and I don't think it's necessary. Let me know if such comparison table based on `pytorch-meta` is provided elsewhere. Thanks!

**Comment by tristandeleu** [comment]
Hi! Torchmeta only features data-loaders and tools to work with meta-learning, but unfortunately it doesn't feature actual implementations of meta-learning algorithms (except for the examples, but they are not guaranteed to have matching performances).

For MAML in particular, I would love to have such a table in [pytorch-maml](https://github.com/tristandeleu/pytorch-maml), which is based on Torchmeta, if time permits!

**Comment by eugenelet** [comment]
Hi! Thanks for the reply. I'm thinking that the results of the implementations would be sufficient. Probably an empty table provided for researchers that uses Torchmeta to contribute to if they made a re-implementation of some algorithms using Torchmeta. This would encourage the quick adoption of Torchmeta in their meta-learning pipeline for publication purpose.

**Comment by tristandeleu** [comment]
These kinds of contributions would be great, and are welcome!
I am closing this issue for now, but feel free (or anyone reading this) to open a PR if you have your own reproduction of meta-learning algorithms using Torchmeta, I would love to include it here (with links to their implementations).
