### ISSUE TITLE
Can not pass None as argument for target_transform for a dataset.

### ISSUE THREAD

**Issue by tesfaldet** [tristandeleu/pytorch-meta#27]
I've been wanting to implement label-conditioning for certain meta learning tasks, and at the moment, it seems that targets always have to be transformed such that the labels are between 0 - num_classes. If I pass None, then try to fetch inputs and targets, the error below appears:

`dataset = DoubleMNIST(..., target_transform=None, ...)`
`dataset = ClassSplitter(dataset, ...)`
`dataloader = BatchMetaDataLoader(dataset, ...)`
`inputs, targets = iter(dataloader).next()['train']`

`TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'NoneType'>`

I've been looking into it, and it seems that if you pass None, a `FixedCategory(None)` object is created and applied to the target over here:

https://github.com/tristandeleu/pytorch-meta/blob/10a34d8ec6d8217517033ff2e04a3138c986e3e1/torchmeta/datasets/doublemnist.py#L243-L246

`(image, target)` is returned, where `target` is changed to `(label, None)`, which eventually causes Pytorch's `default_collate` function to raise a TypeError once it gets to the `None` type.

https://github.com/pytorch/pytorch/blob/9d94f56ce02a814fb3c9dfe3fee675420a7e7e30/torch/utils/data/_utils/collate.py#L77-L81

Otherwise, if you pass a Categorical target transform, a `Compose` object containing that transform is applied to the target, returning `(image, transformed_target)`.

The DoubleMNIST dataset is just one example, as this applies to all datasets that apply a target transform. I was going to modify the check:

https://github.com/tristandeleu/pytorch-meta/blob/10a34d8ec6d8217517033ff2e04a3138c986e3e1/torchmeta/datasets/doublemnist.py#L243

to `if self.target_transform.transform is not None` but that breaks if you provide a target transform, since Compose objects don't have the `transform` property. Also, I believe the line above is redundant anyways, since a target transform always exists? Even if not provided. Maybe this can be changed somehow?

**Comment by tristandeleu** [comment]
> `(image, target)` is returned, where `target` is changed to `(label, None)`, which eventually causes Pytorch's `default_collate` function to raise a TypeError once it gets to the `None` type.

This implicit transformation of `target` is to handle the class augmentations. That's indeed a bad default behavior that it crashes with `target_transform=None`. One solution could be to have a default target transform that is reasonable (in that it can handle the class augmentations) and that works with `BatchMetaDataLoader` (for example have a default target transform that maps the labels to integers).

**Comment by tesfaldet** [comment]
It seems your PR solves the issue on my end! I'm curious about how it all works, but that'll take some more time digging and tracing through the code. Thanks for the quick response!

**Comment by tristandeleu** [comment]
Perfect, glad to hear that! I've made a new release (1.3.3) with this new default.
The inner workings of the library can be a bit confusing, and it is unfortunately not as documented as I would have liked.
