### ISSUE TITLE
Pascal5i Fewshot Segmentation

### ISSUE THREAD

**Issue by MSiam** [tristandeleu/pytorch-meta#29]
Thanks for the great work.

I am wondering if I can add a loader for pascal5i dataset as a pull request? I think it will greatly benefit the fewshot segmentation community to have it in that repo too.

**Comment by tristandeleu** [comment]
That would be a great addition! Feel free to open a PR. Have a look at how the [Omniglot dataset](https://github.com/tristandeleu/pytorch-meta/blob/master/torchmeta/datasets/omniglot.py) works for an example of data-loader.
