### ISSUE TITLE
Cannot pass None as argument for target for a dataset.

### ISSUE THREAD

**Issue by carmete** [tristandeleu/pytorch-meta#35]
Similar issue as https://github.com/tristandeleu/pytorch-meta/issues/27 just with `transform=None`:

```python
from torchmeta.datasets import Omniglot
from torchmeta.transforms import Categorical, ClassSplitter
from torchmeta.utils.data import BatchMetaDataLoader

dataset = Omniglot("data",
                   num_classes_per_task=5,
                   transform=None,
                   target_transform=Categorical(num_classes=5),
                   class_augmentations=[Rotation([90, 180, 270])],
                   meta_train=True,
                   download=True)
dataset = ClassSplitter(dataset, shuffle=True, num_train_per_class=5, num_test_per_class=15)
dataloader = BatchMetaDataLoader(dataset, batch_size=16, num_workers=4)
inputs, targets = iter(dataloader).next()['train']
```
results in
`TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'PIL.Image.Image'>`

Would it be desirable to catch this case?

**Comment by tristandeleu** [comment]
This one is intended behavior, in the sense that it matches the behavior from standard torchvision/PyTorch. To be compatible with the data-loader, it requires at least `transform=ToTensor()`.
