### ISSUE TITLE
CombinationRandomSampler does not have __len__ or _num_samples

### ISSUE THREAD

**Issue by gdahia** [tristandeleu/pytorch-meta#52]
When using `pytorch-meta` with `pytorch-lightning`, we get an `AttributeError` because `pytorch-lightning` calls `len(sampler)` and breaks for the `CombinationRandomSampler` because it neither defines `__len__` nor [`_num_samples`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L99).

This is not a bug from `pytorch-meta`, but I think it would be nice if the libraries interoperate. I also believe that adding this feature would be as easy as adding
```python3
def __len__(self):
  num_classes = len(self.data_source.dataset)
  num_classes_per_task = self.data_source.num_classes_per_task
  return math.comb(num_classes, num_classes_per_task)
```

I could open a PR with an implementation that works for other Python versions if you are interested in adding this feature. Thanks.

**Comment by tristandeleu** [comment]
Thanks for the bug report! Compatibility with other packages is definitely important, especially with something as widely used as `pytorch-lightening`, and it looks like a great update. A PR would be very appreciated, thank you very much! Another option could also be to call directly `len(self.data_source)`, since [`CombinationMetaDataset` does define `__len__`](https://github.com/tristandeleu/pytorch-meta/blob/b4a30adb66fe926ae9c28d4fc50b3d374350ec77/torchmeta/utils/data/dataset.py#L295-L299).

**Comment by gdahia** [comment]
I think your suggestion is an improvement over mine, but digging a little deeper, it seems to me that calling `super(Sampler, self).__init__(data_source)` for `Sampler=CombinationRandomSampler` and `Sampler=CombinationSequentialSampler` would solve the problem because both [`RandomSampler`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L68-L110) and [`SequentialSampler`](https://github.com/pytorch/pytorch/blob/master/torch/utils/data/sampler.py#L51-L65) define `__len__` in a compatible way.

While I am at it, I could also add error messages to the `ValueError` when the `data_source` is not a `CombinationMetaDataset`. Does that sound good to you? Thanks.

**Comment by tristandeleu** [comment]
That is indeed a much simpler solution.

> While I am at it, I could also add error messages to the `ValueError` when the `data_source` is not a `CombinationMetaDataset`. Does that sound good to you? Thanks.

That would be great, thanks!
