### ISSUE TITLE
Reproducibility is broken with class augmentations

### ISSUE THREAD

**Issue by marcociccone** [tristandeleu/pytorch-meta#56]
Hi!
Even if you fix the random seed everywhere, when you use class augmentations such as `Rotation([90, 180, 270])`, results are not always the same. 
It took me a  while, but I found that it is because class augmentations become unique using a `set()`, [here](https://github.com/tristandeleu/pytorch-meta/blob/ca269276a6b210b72e65be0d4cde0629485b1140/torchmeta/utils/data/dataset.py#L70) and this is not stable. 
The order of the augmentations might not be the same at different runs!

**Comment by tristandeleu** [comment]
Hi! That's a very good point, thank you. It should probably be just a matter of switching `set()` for `OrderedSet()`.

**Comment by marcociccone** [comment]
Yes, you're right, but I only found an external [pip package OrderedSet](https://pypi.org/project/ordered-set/). Or if you prefer I can find an alternative. 
I can test it and submit a PR if that is ok for you.

**Comment by tristandeleu** [comment]
I think this additional dependency doesn't hurt too much, and would probably be easiest solution. That would be great if you could open a PR with it, thank you!
