### ISSUE TITLE
Matching Networks?

### ISSUE THREAD

**Issue by akreal** [tristandeleu/pytorch-meta#60]
Would you be interested to include an example with Matching Networks (https://arxiv.org/abs/1606.04080)? I've ported the existing implementation (https://github.com/BoyuanJiang/matching-networks-pytorch) in order to have more comparisons, but currently without Full Context Embeddings and only on Omniglot dataset.

**Comment by tristandeleu** [comment]
That would be a great addition! Feel free to open a PR with the new example

**Comment by akreal** [comment]
Cool, thanks! And thank you for your great library!
