### ISSUE TITLE
What does "MiniImagenet integrity check failed" mean?

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-meta#64]
What does "MiniImagenet integrity check failed" mean?

**Comment by tristandeleu** [comment]
It could be one of two issues:
 - You didn't include `download=True` to download the dataset (by default, `download=False`, following the conventions of Torchvision). It would look something like `dataset = miniimagenet(..., meta_train=True, download=True)`.
 - If you did include `download=True`, this means that there was an issue with the dataset conversion. If you have a subfolder `miniimagenet` in your data folder, then delete it and try to run it again.
