### ISSUE TITLE
where do automatic downloaders download the data to?

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-meta#65]
where do automatic downloaders download the data to?

**Comment by renesax14** [comment]
had to look into the code and it uses root. Please improv docs.

**Comment by tristandeleu** [comment]
The documentation could definitely use some work. However this particular information is already available in [the docs ("download")](https://tristandeleu.github.io/pytorch-meta/api_reference/datasets/#miniimagenet)

**Comment by renesax14** [comment]
> The documentation could definitely use some work. However this particular information is already available in [the docs ("download")](https://tristandeleu.github.io/pytorch-meta/api_reference/datasets/#miniimagenet)

I think the docs are confusing. It says:

```
root: string
Root directory where the dataset folder miniimagenet exists.
```

Does that mean I need to make a folder with that name before hand? Or does it make it itself? Do you I need to provide the directory to where data sets live and then it creates by itself the `miniimagenet` folder?

There is something talking about docs but to imprecise to be used using only the docs.

I am happy to help :)
