### ISSUE TITLE
add in the example folder something with mini-imagent?

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-meta#66]

**Comment by tristandeleu** [comment]
You can switch the dataset in any of the examples with Mini-Imagenet. This would require most likely to change the architecture of the network as well to account for the image size. If you want a full example with different datasets, please have a look at the [pytorch-maml repo](https://github.com/tristandeleu/pytorch-maml).

**Comment by renesax14** [comment]
> You can switch the dataset in any of the examples with Mini-Imagenet. This would require most likely to change the architecture of the network as well to account for the image size. If you want a full example with different datasets, please have a look at the [pytorch-maml repo](https://github.com/tristandeleu/pytorch-maml).

Fantastic thanks! 👯
