### ISSUE TITLE
Compatibility with pytorch 1.3

### ISSUE THREAD

**Issue by stepelu** [tristandeleu/pytorch-meta#7]
`setup.py` explicitly restrict pytorch to  < 1.3, is it a conservative check?

**Comment by tristandeleu** [comment]
It is conservative in the sense that `MetaModule` implementations are based on the implementations of `nn.Module` in PyTorch 1.2. I haven't checked how this changes in 1.3, but chances are it would still work in PyTorch 1.3. I will update that as soon as possible.

PyTorch 1.3 also introduces new features for dataloaders which might be of interest for Torchmeta, so a more general update is to be expected as well to make full use of the latest features.

**Comment by tristandeleu** [comment]
I have upgraded the requirement for PyTorch in the latest version of Torchmeta. It now requires PyTorch>=1.3.0
