### ISSUE TITLE
Clarification of term episodic vs meta-set vs meta-batching

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-meta#78]
I think I asked this somewhere but can't find it easily and I think it's important.

When we have a meta-set (a data-set of data-sets with support & query splits) `D_meta = {D_i}^N_{i=1}` is the index `i` called an episode or is an episode a (meta) batch (of data-sets) from this meta-set (e.g. of size `16`)?

cross posted: https://stats.stackexchange.com/questions/478255/what-does-the-term-episode-mean-in-meta-learning

**Comment by tristandeleu** [comment]
Usually an episode means one single dataset `D_i`. If you have a (meta-)batch of size 16, this means you have 16 episodes/datasets in your (meta-)batch.

**Comment by renesax14** [comment]
> Usually an episode means one single dataset `D_i`. If you have a (meta-)batch of size 16, this means you have 16 episodes/datasets in your (meta-)batch.

Do you have a quote to cite that? Just want to be sure.

Thanks for your helpful replies Trist! :)

**Comment by renesax14** [comment]
> Usually an episode means one single dataset `D_i`. If you have a (meta-)batch of size 16, this means you have 16 episodes/datasets in your (meta-)batch.

if your definition is right then this should be the right way to loop through the data:

```
# looping through metasets

from torchmeta.utils.data import BatchMetaDataLoader
from torchmeta.transforms import ClassSplitter
from torchmeta.toy import Sinusoid

from tqdm import tqdm

# get data set
dataset = Sinusoid(num_samples_per_task=25, num_tasks=30)
shots, test_shots = 5, 15
# get metaset
metaset = ClassSplitter(
    dataset,
    num_train_per_class=shots,
    num_test_per_class=test_shots,
    shuffle=True)
# get meta-dataloader
batch_size = 16
num_workers = 0
meta_dataloader = BatchMetaDataLoader(metaset, batch_size=batch_size, num_workers=num_workers)
epochs = 2

print(f'batch_size = {batch_size}')
print(f'len(metaset) = {len(metaset)}')
print(f'len(meta_dataloader) = {len(meta_dataloader)}')
with tqdm(range(epochs)) as tepochs:
    for epoch in tepochs:
        for batch_idx, batch in enumerate(meta_dataloader):
            print(f'\nbatch_idx = {batch_idx}')
            train_inputs, train_targets = batch['train']
            test_inputs, test_targets = batch['test']
            print(f'train_inputs.shape = {train_inputs.shape}')
            print(f'train_targets.shape = {train_targets.shape}')
            print(f'test_inputs.shape = {test_inputs.shape}')
            print(f'test_targets.shape = {test_targets.shape}')
```

**Comment by tristandeleu** [comment]
The snippet above looks about right!

>Do you have a quote to cite that? Just want to be sure.

In [Meta-Learning with Memory-Augmented Neural Networks](http://proceedings.mlr.press/v48/santoro16.pdf), Section 2:
> In our setup, a task, or episode, involves the presentation of some dataset `D = {d_t}_{t=1}^{T} = {(xt, yt)}_{t=1}^{T}`.

**Comment by renesax14** [comment]
> The snippet above looks about right!
> 
> > Do you have a quote to cite that? Just want to be sure.
> 
> In [Meta-Learning with Memory-Augmented Neural Networks](http://proceedings.mlr.press/v48/santoro16.pdf), Section 2:
> 
> > In our setup, a task, or episode, involves the presentation of some dataset `D = {d_t}_{t=1}^{T} = {(xt, yt)}_{t=1}^{T}`.

this is the quote I find unreadable:

```
More specifically, let us define a task T as distribution over possible label sets L. Typically we consider T to uniformly weight all data sets of up to a few unique classes (e.g., 5), with a few examples per class (e.g., up to 5). In this case, a label set L sampled from a task T , L ∼ T , will typically have 5 to 25 examples.
To form an “episode” to compute gradients and update our model, we first sample L from T (e.g.,
L could be the label set {cats, dogs}). We then use L to sample the support set S and a batch B
(i.e., both S and B are labelled examples of cats and dogs). The Matching Net is then trained to
minimise the error predicting the labels in the batch B conditioned on the support set S. This is a
form of meta-learning since the training procedure explicitly learns to learn from a given support set
to minimise a loss over a batch.
```

**Comment by renesax14** [comment]
@tristandeleu is this correct?

Regression:
`num_iterations in 1 epoch = ceil( num_tasks/meta-batches )`
classification (N-way, K-shot):
`num_iterations in 1 epoch = ceil( num_tasks/(N*meta-batches) )`

**Comment by renesax14** [comment]
@tristandeleu in more detail:

* we have a database of data 
    * mini-imagenet: 64 classes with 600 images
* meta-set
    * a meta-set is created at the beginning of 1 epoch (using the meta-dataloader)
    * we samples say 1 (meta) batches of datasets/tasks 5-way, 5-shot, 15-eval
        * each using 20 images of the 600 per class
    * iterations/#of batches = ceil(64/(5*1)) = 13 (last with 4 classes)
* meta-dataloader
    * creates a meta-set & gets batches based on # class available/(meta-batchsize * N) = # batches (iterations within 1 epoch) 
        * one task/episode with N classes and K shots, K'-evals
    * this meta-dataloader finishes when # epochs is reached

**Comment by renesax14** [comment]
> Usually an episode means one single dataset `D_i`. If you have a (meta-)batch of size 16, this means you have 16 episodes/datasets in your (meta-)batch.

I don't think this is right. An episode I think should be 1 iteration so 1 collection of tasks (a meta-batch).

Otherwise a task and an episode are the same term and it seems redundant to have the term episode.

**Comment by tristandeleu** [comment]
I agree with your definition of batch of tasks, but this does not correspond to an episode (see my comment above https://github.com/tristandeleu/pytorch-meta/issues/78#issuecomment-662343834). Do you have a reference for an episode being a batch of tasks?

Defining an episode as being a single task refers to [episodic learning](https://en.wikipedia.org/wiki/Episodic_memory), where your episode represents the whole experience you get to see to learn to solve a task.
