### ISSUE TITLE
Put toy in the dataset directory

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-meta#79]
the toy datasets are still datasets.

I suggest to move it there to make the imports and traversing the library easier.

Thanks for this great library.

**Comment by tristandeleu** [comment]
The `toy` directory is meant for toy tasks that are generated, as opposed to `datasets` with a fixed meta-train/meta-validation/meta-test splits. I would prefer keeping the two separate, instead of having everything inside `datasets`.
