### ISSUE TITLE
where is self.np_random being assigned?

### ISSUE THREAD

**Issue by renesax14** [tristandeleu/pytorch-meta#81]
it is not in the constructor

https://github.com/tristandeleu/pytorch-meta/blob/9d34b837440df4e3790fc2faaffaacfa257f4223/torchmeta/toy/sinusoid.py#L48

so it's being assigned out of the blue somewhere else. Why? this seems dangerous and hard to read/maintain.

**Comment by tristandeleu** [comment]
This is defined in the parent class `MetaDataset` here: https://github.com/tristandeleu/pytorch-meta/blob/9d34b837440df4e3790fc2faaffaacfa257f4223/torchmeta/utils/data/dataset.py#L200-L203
