### ISSUE TITLE
Checkpoints for all data sets

### ISSUE THREAD

**Issue by brando90** [tristandeleu/pytorch-meta#90]
Hi,

I was wondering if checkpoints could be made available for some of the datasets.

I am in particular interested in mini-imagenet checkpoints trained with MAML.

Though, honestly, the more checkpoints with more meta-learning algorithms the better.

**Comment by tristandeleu** [comment]
Hi, sorry but the examples provided in this repository are only meant to show how to use Torchmeta, and they are not meant to be fully operational implementations of the corresponding algorithms. Getting checkpoints for these is unfortunately outside of the scope of this library.

**Comment by brando90** [comment]
@tristandeleu hi tristand, I remember you mentioned that you did reproduce the 63% acc that MAML got on imagenet. I was wondering if you had that checkpoint available?

Thanks for your time.
