### ISSUE TITLE
Tiered-ImageNet  download doesnt seem to be working

### ISSUE THREAD

**Issue by sudarshan1994** [tristandeleu/pytorch-meta#92]
`TieredImagenet('data',meta_train= True,download = True)`, just seems to download an empty tar file, consequently I see this error : file could not be opened successfully at line 184 in tieredimagenet.py

Any Clarification would be super helpful ! thanks !

**Comment by tristandeleu** [comment]
This is most likely due to the quota being exceeded on Google Drive. See #54 for a similar issue on MiniImagenet.
Unfortunately there is no fix for that other than waiting for the quota to be renewed.
