### ISSUE TITLE
MetaModule for nn.Embedding

### ISSUE THREAD

**Issue by richielo** [tristandeleu/pytorch-meta#93]
As titled, how should I go about implementing MetaModule for nn.Embedding? Do I simply inherent MetaModule and use nn.functional's support to do so?

I am trying to use torchmeta on nlp problems. It'd be great to add the support for nn.Embedding

Thanks a lot!

**Comment by tristandeleu** [comment]
This is a great suggestion, and it should be easy enough to implement. I'll add that to the meta-modules today.

**Comment by tristandeleu** [comment]
I have added `MetaEmbedding` and `MetaEmbeddingBag` as `MetaModule` equivalents of `nn.Embedding` and `nn.EmbeddingBag` in master.

**Comment by richielo** [comment]
Awesome! Thanks for the quick response!!
