### ISSUE TITLE
Feature suggestion: Add flag to module.get_subdict to return None instead of empty OrderedDict

### ISSUE THREAD

**Issue by SebGruber1996** [tristandeleu/pytorch-meta#94]
i have currently the issue of calling a key that is not existent in a parameter dictionary like this:
```
p = self.get_subdict(params, "features")
```
of course it makes sense as the default behavior to return an empty OrderedDict.
But unfortunately when I call forward propagation with `p`, it is not handled as `NoneType` and leads to an error:
```
features = self.features(
    input, params=p
)
```
My work-around procedure looks like this, but is quite ugly:
```
p = self.get_subdict(params, "features")
if p is not None and len(p)==0:
    p = None
```
instead something along the following, which would simply force `None` as return instead of an empty OrderedDict, would greatly improve the aesthetics of the code:
```
p = self.get_subdict(params, "features", force_None=True)
```

**Comment by tristandeleu** [comment]
It seems reasonable to always return `None` instead of an empty dictionary (without requiring the `force_None` argument). I just need to make sure nothing breaks with this change, but that sounds like a good suggestion thanks!

**Comment by tristandeleu** [comment]
I have updated `get_subdict` to return `None` when the key is not found in `params`. However I have left a warning to let the user know that the key was not found and it rolls back to the default parameters from the module. Let me know what you think about this.
https://github.com/tristandeleu/pytorch-meta/blob/4e29b39cc21d1846c6266ac1c113e3c2233276d0/torchmeta/modules/module.py#L56-L64

**Comment by SebGruber1996** [comment]
`None` makes sense to be the default! I was also worried that this breaks something somewhere else.
Even though, I am unsure about receiving the warning every possible forward propagation (this is how often subdict is called in my case, but I don't wanna speak for everybody).
Only time will tell what's best.
Thanks a lot for the quick action - changes like these make the package nicer to use!

**Comment by tristandeleu** [comment]
It depends on your use case, but I think unless the keys of the params dictionary change at every call to forward, you should only get a single warning for the first call to forward. Let me know if that's not the case.
