### ISSUE TITLE
Can I use this repo in time series regression or classification?

### ISSUE THREAD

**Issue by sunfu12** [tristandeleu/pytorch-meta#96]
I want to use meta learning in time series (such as stock price) regression or classification, can I use this repo? How to do it?

**Comment by tristandeleu** [comment]
This library provides dataloaders for both [regression problems](https://github.com/tristandeleu/pytorch-meta/tree/master/torchmeta/toy) and [classification problems](https://github.com/tristandeleu/pytorch-meta/tree/master/torchmeta/datasets), so you can use it for both type of problems. If you want to create your own dataset (for stock price), then I suggest you have a look at the [Sinusoid](https://github.com/tristandeleu/pytorch-meta/blob/6db28dc9e7e22c8f6239169c2ce0761e87d5a1b3/torchmeta/toy/sinusoid.py) dataset for inspiration.
