### ISSUE TITLE
Bug with dataparallel in Pytorch 1.6

### ISSUE THREAD

**Issue by zhangmozhe** [tristandeleu/pytorch-meta#97]
Hi, thanks for providing this cool library! We successfully implement the meta-learning where hypernet generates weights for the hyponet. The code runs successfully on single GPU. When we apply Dataparallel, it prompts:

  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanbo/Work/point_codebase/models/FoldingMLP.py", line 133, in forward
    hypo_params = self.hyper_net[i](x)
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanbo/Work/point_codebase/models/meta_modules_old.py", line 63, in forward
    params[name] = net(z).reshape(batch_param_shape)
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanbo/Work/point_codebase/models/meta_modules_old.py", line 197, in forward
    output = self.net(coords, params=self.get_subdict(params, "net"))
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torchmeta/modules/container.py", line 12, in forward
    input = module(input, params=self.get_subdict(params, name))
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torchmeta/modules/container.py", line 12, in forward
    input = module(input, params=self.get_subdict(params, name))
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhanbo/Work/point_codebase/models/meta_modules_old.py", line 78, in forward
    weight = params["weight"]
KeyError: 'weight'

We have found this error arises from the bug of Pytorch 1.6 (https://github.com/pytorch/pytorch/issues/36035), where ParameterList appears empty in the forward pass. Do you have any workaround solution? Thanks!

**Comment by tristandeleu** [comment]
Thank you for the kind words! Are you applying `nn.DataParallel` from PyTorch directly to a MetaModule? If so, you should consider using the [`DataParallel` wrapper](https://github.com/tristandeleu/pytorch-meta/blob/0984c0150a58e4f01624898513fe81461485d64e/torchmeta/modules/parallel.py) from Torchmeta, which should take care of this issue (using `from torchmeta.modules import DataParallel`, it has the same API as the standard `nn.DataParallel`).

**Comment by zhangmozhe** [comment]
Thanks for your reply. We indeed apply the torchmeta.modules.DataParallel, and we have make sure that the library is up-to-date, but there still prompts the error.

**Comment by zhangmozhe** [comment]
Here is part of the code.

```
class BatchLinear(nn.Linear, MetaModule):
    """A linear meta-layer that can deal with batched weight matrices and biases, as for instance output by a
    hypernetwork."""

    __doc__ = nn.Linear.__doc__

    def forward(self, input, params=None):
        if params is None:
            params = OrderedDict(self.named_parameters())

        bias = params.get("bias", None)
        weight = params["weight"]

        output = input.matmul(weight.permute(*[i for i in range(len(weight.shape) - 2)], -1, -2))
        output += bias.unsqueeze(-2)
        return output

class FCBlock(MetaModule):
    """A fully connected neural network that also allows swapping out the weights when used with a hypernetwork.
    Can be used just as a normal neural network though, as well.
    """

    def __init__(
        self,
        in_features,
        out_features,
        num_hidden_layers,
        hidden_features,
        outermost_linear=False,
        nonlinearity="relu",
        weight_init=None,
    ):
        super().__init__()

        self.first_layer_init = None

        # Dictionary that maps nonlinearity name to the respective function, initialization, and, if applicable,
        # special first-layer initialization scheme
        nls_and_inits = {
            "sine": (Sine(), sine_init, first_layer_sine_init),
            "relu": (nn.ReLU(inplace=True), init_weights_normal, None),
            "sigmoid": (nn.Sigmoid(), init_weights_xavier, None),
            "tanh": (nn.Tanh(), init_weights_xavier, None),
            "selu": (nn.SELU(inplace=True), init_weights_selu, None),
            "softplus": (nn.Softplus(), init_weights_normal, None),
            "elu": (nn.ELU(inplace=True), init_weights_elu, None),
        }

        nl, nl_weight_init, first_layer_init = nls_and_inits[nonlinearity]

        if weight_init is not None:  # Overwrite weight init if passed
            self.weight_init = weight_init
        else:
            self.weight_init = nl_weight_init

        self.net = []
        self.net.append(MetaSequential(BatchLinear(in_features, hidden_features), nl,))

        for i in range(num_hidden_layers):
            self.net.append(MetaSequential(BatchLinear(hidden_features, hidden_features), nl,))

        if outermost_linear:
            self.net.append(MetaSequential(BatchLinear(hidden_features, out_features)))
        else:
            self.net.append(MetaSequential(BatchLinear(hidden_features, out_features), nl))

        self.net = MetaSequential(*self.net)
        if self.weight_init is not None:
            self.net.apply(self.weight_init)

        if first_layer_init is not None:  # Apply special initialization to first layer, if applicable.
            self.net[0].apply(first_layer_init)

    def forward(self, coords, params=None, **kwargs):
        if params is None:
            params = OrderedDict(self.named_parameters())

        output = self.net(coords, params=self.get_subdict(params, "net"))
        return output
```

**Comment by tristandeleu** [comment]
Oh indeed, there seems to be an issue with `self.get_subdict` and `DataParallel`, thank you for reporting!
I will look into how to fix it, and I'll let you know.

**Comment by tristandeleu** [comment]
As a temporary fix, you can remove the `module.` prefix in all the keys of your parameter dictionary before feeding it to forward. That's a prefix that `DataParallel` adds to the parameter names, and that isn't handled properly in the cache of MetaModule. You can do something like
```python
params = OrderedDict([(name[7:], param) for (name, param) in params.items()])
```

**Comment by tristandeleu** [comment]
This should be fixed in master, and in the new release Torchmeta 1.5.3.

**Comment by zhangmozhe** [comment]
Thanks for your help, the new version works now. BTW, it seems that the multi-gpu utilization is highly imbalanced, and do you have any idea about it?

**Comment by tristandeleu** [comment]
That's indeed still an issue with the additional prefix `module.` in the parameter keys. The fix in https://github.com/tristandeleu/pytorch-meta/issues/97#issuecomment-707118349 should still work for you here. I did test the full `FCBlock` in your earlier comment, and that seemed to work though. I'll try to fix this remaining issue.

**Comment by tristandeleu** [comment]
Can you try with the [`fix/dataparallel`](https://github.com/tristandeleu/pytorch-meta/tree/fix/dataparallel) branch, and tell me if that solves your issue? I have tried it on my end and it seems to do the trick.

**Comment by zhangmozhe** [comment]
I have checked the code but still cannot work. OrderedDict(self.named_parameters()) gives OrderedDict([]). A workaround is manually choose nn.Linear when OrderedDict([]).

```
class BatchLinear(nn.Linear, MetaModule):
    """A linear meta-layer that can deal with batched weight matrices and biases, as for instance output by a
    hypernetwork."""

    __doc__ = nn.Linear.__doc__

    def forward(self, input, params=None):
        if params is None:
            return nn.Linear.forward(self, input)
        else:
            bias = params.get("bias", None)
            weight = params["weight"]

            output = input.matmul(weight.permute(*[i for i in range(len(weight.shape) - 2)], -1, -2))
            output += bias.unsqueeze(-2)
            return output
```

**Comment by tristandeleu** [comment]
This is the snippet of code I have and works as expected on my end with this branch:
```python
import torch.nn as nn

from torchmeta.modules import MetaModule
from collections import OrderedDict


class BatchLinear(nn.Linear, MetaModule):
    """A linear meta-layer that can deal with batched weight matrices and biases, as for instance output by a
    hypernetwork."""

    __doc__ = nn.Linear.__doc__

    def forward(self, input, params=None):
        if params is None:
            params = OrderedDict(self.named_parameters())

        bias = params.get("bias", None)
        weight = params["weight"]

        output = input.matmul(weight.permute(*[i for i in range(len(weight.shape) - 2)], -1, -2))
        output += bias.unsqueeze(-2)
        return output


if __name__ == '__main__':
    import torch
    import torchmeta

    from torchmeta.modules import DataParallel
    from torchmeta.utils.gradient_based import gradient_update_parameters

    print(f'Torch version: {torch.__version__}')
    print(f'Torchmeta version: {torchmeta.__version__}')

    print(f'CUDA is available: {torch.cuda.is_available()}')
    print(f'Number of devices: {torch.cuda.device_count()}')

    model = BatchLinear(in_features=3, out_features=5)
    model.to(device='cuda:0')
    model = DataParallel(model)

    train_inputs = torch.randn(7, 11, 3, device='cuda:0')
    train_outputs = model(train_inputs, params=None)

    print(f'Train outputs shape: {train_outputs.shape}')

    inner_loss = train_outputs.sum()  # Dummy loss
    params = gradient_update_parameters(model, inner_loss)

    test_inputs = torch.randn(7, 11, 3, device='cuda:0')
    test_outputs = model(test_inputs, params=params)

    print(f'Test outputs shape: {test_outputs.shape}')

    outer_loss = test_outputs.sum()  # Dummy loss
    outer_loss.backward()

    # Outputs
    # Torch version: 1.6.0
    # Torchmeta version: 1.5.3
    # CUDA is available: True
    # Number of devices: 2
    # Train outputs shape: torch.Size([7, 11, 5])
    # Test outputs shape: torch.Size([7, 11, 5])
```
If this still doesn't work, then can you attach the full (minimal) code you are running (not just the model).

**Comment by zhangmozhe** [comment]
Below is the code with error

```
from collections import OrderedDict

import torch.nn as nn
from torchmeta.modules import MetaModule


class BatchLinear(nn.Linear, MetaModule):
    """A linear meta-layer that can deal with batched weight matrices and biases, as for instance output by a
    hypernetwork."""

    __doc__ = nn.Linear.__doc__

    def forward(self, input, params=None):
        if params is None:
            params = OrderedDict(self.named_parameters())

        bias = params.get("bias", None)
        weight = params["weight"]

        output = input.matmul(weight.permute(*[i for i in range(len(weight.shape) - 2)], -1, -2))
        output += bias.unsqueeze(-2)
        return output


class FCBlock(MetaModule):
    def __init__(
        self, in_features, out_features,
    ):
        super().__init__()
        self.net = []
        self.net.append(MetaSequential(BatchLinear(in_features, out_features)))
        self.net = MetaSequential(*self.net)

    def forward(self, coords, params=None, **kwargs):
        if params is None:
            params = OrderedDict(self.named_parameters())

        output = self.net(coords, params=self.get_subdict(params, "net"))
        return output


class Model(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.hypernet = nn.ModuleList([FCBlock(in_features=in_features, out_features=out_features,)])
        self.hypernet = FCBlock(in_features=in_features, out_features=out_features,)

    def forward(self, x):
        out = self.hypernet(x)
        return out


if __name__ == "__main__":
    import torch
    import torchmeta
    from torchmeta.modules import DataParallel, MetaSequential
    # from torchmeta.modules.module import get_subdict
    from torchmeta.utils.gradient_based import gradient_update_parameters

    print(f"Torch version: {torch.__version__}")
    print(f"Torchmeta version: {torchmeta.__version__}")

    print(f"CUDA is available: {torch.cuda.is_available()}")
    print(f"Number of devices: {torch.cuda.device_count()}")

    model = Model(in_features=3, out_features=5)
    model.to(device="cuda:0")
    model = DataParallel(model)

    train_inputs = torch.randn(7, 11, 3, device="cuda:0")
    train_outputs = model(train_inputs)
    print(f"Train outputs shape: {train_outputs.shape}")

```

**Comment by tristandeleu** [comment]
The issue is that your `Model` class inherits from a `nn.Module` instead of being a `MetaModule`, so `DataParallel` from Torchmeta works exactly like `nn.DataParallel` from PyTorch (and you end up getting the same issue as the one in the issue you linked to earlier).

Changing your `Model` class to
```python
class Model(MetaModule):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.hypernet = nn.ModuleList([FCBlock(in_features=in_features, out_features=out_features,)])
        self.hypernet = FCBlock(in_features=in_features, out_features=out_features,)

    def forward(self, x, params=None):
        if params is None:
            params = OrderedDict(self.named_parameters())

        out = self.hypernet(x, params=self.get_subdict(params, 'hypernet'))
        return out
```
does the trick.

**Comment by zhangmozhe** [comment]
When I change the class to `MetaModule`, it still prompts the error:

Caught TypeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/zhanbo/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'params'

**Comment by tristandeleu** [comment]
Did you also change the `forward` function?
The code you have attached, when replacing the whole `Model` class by the one I gave in https://github.com/tristandeleu/pytorch-meta/issues/97#issuecomment-708351206, works for me.

**Comment by zhangmozhe** [comment]
Now it works. Thanks for your help very much!
